about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('', views.about, name='about'),
]

books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.books, name='books'),
    path('books.json', views.get_data, name='json'),
]

nextstory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('status.urls')),
    path('about/', include('about.urls')),
    path('books/', include('books.urls')),
]

status/urls.py
from django.urls import path
from . import views

app_name = 'status'

urlpatterns = [
    path('', views.status, name='home'),
    path('confirm/', views.konfirmasi, name='confirm'),
    path('color/<int:index>/', views.colorChange)
]

about/models.py
from django.db import models

# Create your models here.

books/models.py
from django.db import models

# Create your models here.

class Books(models.Model):
    id_buku = models.CharField('nama', max_length=200)
    cover = models.CharField('cover', max_length=300, null=True)
    title = models.CharField('title', max_length=200, null=True)
    authors = models.CharField('authors', max_length=200, null=True)
    jumlah_like = models.IntegerField('jumlah like')
    

status/models.py
from django.db import models

# Create your models here.

class Status(models.Model):
    nama = models.CharField('nama', max_length=50)
    pesan = models.TextField('pesan', max_length=200)
    color = models.CharField('color', max_length=8, null=True)

status/forms.py
from django.forms import ModelForm, forms, Textarea
from .models import Status

class StatusForm(ModelForm):
    class Meta:
        model = Status
        fields = ['nama', 'pesan']

about/views.py
from django.shortcuts import render

def about(request):
    return render(request, 'about.html')

books/views.py
from django.shortcuts import render
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponseForbidden, HttpResponse
from django.forms.models import model_to_dict
import requests
from json import loads
from .models import Books

def books(request):
    return render(request, 'books.html')

def get_data(request):
    if request.method == "POST":
        idBuku = request.POST.get('id')
        url = "https://www.googleapis.com/books/v1/volumes?q=" + idBuku
        books_json = requests.get(url).json().get("items")[0]
        try:
            obj = Books.objects.get(id_buku = idBuku)
            obj.jumlah_like += 1
            obj.save()
        except Books.DoesNotExist:
            obj = Books(
                id_buku = idBuku,
                cover = books_json.get("volumeInfo").get("imageLinks").get("smallThumbnail"),
                title = books_json.get("volumeInfo").get("title"),
                authors = books_json.get("volumeInfo").get("authors"),
                jumlah_like = 1
            )
            obj.save()
        
        context = model_to_dict(obj, fields=[field.name for field in obj._meta.fields])
        return JsonResponse({"local_json" : context})


    else:
        url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET.get('keyword')
        books_json = requests.get(url).json()
        lst_books = []

        for book in books_json.get("items"):
            try:
                obj = Books.objects.get(id_buku = book.get("id"))
                temp = {
                    "id" : obj.id_buku,
                    "cover" : obj.cover,
                    "title" : obj.title,
                    "authors" : obj.authors,
                    "likes" : obj.jumlah_like
                }

            except:
                img = book.get('volumeInfo').get('imageLinks', None)
                if(img): img = img.get("smallThumbnail", "")
                else: 
                    print("XXXXXXXXXXXXXX KOSONG WEH XXXXXXXXXXXXXX", )
                    print(book.get("volumeInfo").get("title"))
                    print("XXXXXXXXXXXXXX KOSONG WEH XXXXXXXXXXXXXX", )
                temp = {
                    "id" : book.get("id"),
                    "cover" : img,
                    "title" : book.get("volumeInfo").get("title"),
                    "authors" : book.get("volumeInfo").get("authors"),
                    "likes" : 0
                }
            lst_books.append(temp)
        
        return JsonResponse({"items" : lst_books})

status/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import Status
from .forms import StatusForm
import random

# Create your views here.

def status(request):
    if request.method == "POST":
        form = StatusForm(request.POST)
        if form.is_valid():
            request.session['nama'] = form.data['nama']
            request.session['pesan'] = form.data['pesan']
            return redirect('/confirm')
    else:
        form = StatusForm()
        
    context = {
        'status' : Status.objects.all(),
        'form' : form
    }

    return render(request, 'home.html', context)

def colorChange(request, index):
    if request.method == "POST":
        red = (random.randint(150, 250))
        green = (random.randint(150, 250))
        blue = (random.randint(150, 250))
        color = "#%02x%02x%02x" % (red, green, blue)
        obj = Status.objects.get(pk=index)
        obj.color = color
        obj.save()

    return redirect('/')

def konfirmasi(request):
    if request.method == 'POST':
        nama = request.session.get('nama')
        pesan = request.session.get('pesan')
        warna = "#ffffff"
        new_status = Status(
                nama = nama,
                pesan = pesan,
                color = warna
            )

        if nama != None and pesan != None:
            new_status.save()
            del request.session['nama']
            del request.session['pesan']
        
        return redirect('/')
    
    context = {
        'nama' : request.session.get('nama'),
        'pesan' : request.session.get('pesan')
    }

    return render(request, 'confirm.html', context)

about/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %} About {% endblock %}

{% block content %}
<div class="col-sm-2">
  <p>Themes</p>
  <button type="button" class="btn btn-primary" id="light_theme">Light</button>
  <button type="button" class="btn btn-primary" id="dark_theme">Dark</button>
</div>

<h2>a little about myself</h2>

<div class="col-sm-8">
  <!-- accordion =================================================================================== -->
  <div id="accordion">
    <div class="info acc-head">
      <button class="btn" href="#">Personal Information<i class="fa fa-plus"></i></button>
      <div class="btn-group">
        <a href="#" class="down-info btn btn-light up">up</a>
        <a href="#" class="btn btn-light down">down</a>
    </div>
    <div class="content">
        <p>betaorionis</p>
        <p>location: Orion, Milky Way</p>
        <p>u dont hv my contacts? go away.</p>
        <p>status: terdampar di pacil</p>
    </div>
    </div>
  </div>

  <div id="accordion">
    <div class="activity acc-head">
      <button class="btn" href="#">Activity<i class="fa fa-plus"></i></button>
      <div class="btn-group">
        <a href="#" class="btn btn-light up">up</a>
        <a href="#" class="btn btn-light down">down</a>
    </div>
    <div class="content">
      <p>nugas</p>
      <p>nugas lagi</p>
      <p>ketiduran</p>
      <p>bangun panik tugas blm selesai</p>
      <p>nugas lagi</p>
    </div>
    </div>
  </div>

  <div id="accordion">
    <div class="experience acc-head">
      <button class="btn" href="#">Experience<i class="fa fa-plus"></i></button>
      <div class="btn-group">
        <a href="#" class="up-exp btn btn-light up">up</a>
        <a href="#" class="btn btn-light down">down</a>
    </div>
    <div class="content">
      <p>kepeleset</p>
      <p>kejedot meja kelas</p>
      <p>ketiduran trus bangun krn kaget di kelas</p>
    </div>
    </div>
  </div>

  <div id="accordion">
    <div class="achievement acc-head">
      <button class="btn" href="#">Achievement<i class="fa fa-plus"></i></button>
      <div class="btn-group">
        <a href="#" class="btn btn-light up">up</a>
        <a href="#" class="btn btn-light down">down</a>
    </div>
    <div class="content">
      <p>a</p>
      <p>be</p>
      <p>ce</p>
      <p>de</p>
      <p>e</p>
    </div>
    </div>
  </div>

  <!-- ============================================================================ End of accordion -->
</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/about.js' %}"></script>
{% endblock %}

books/templates/books.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <section class="container-fluid pb-5 px-0 min-vh-100 w-100">
        <h2>some books you might want to read</h2>

        <div class="row mx-auto px-5 my-4">
            <input type="text" class="form-control form-control-sm" id="search-box" placeholder="Orion">
            <button id="search-button">Cari</button>
        </div>
        <div class="row mx-auto px-5 my-4">
            <div class="col mx-5" id="output" style="background-color: rgb(211, 227, 238);" name="tabel">
            </div>
        </div>

    </section>
{% endblock %}

{% block script %}
    <script>
        const get_books_url = "{% url 'books:json' %}?keyword=";
    </script>
    <script src="{% static 'js/books.js' %}"></script>
{% endblock %}

status/templates/confirm.html
<!DOCTYPE html>

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <title>Konfirmasi status</title>
</head>
<body>
    <h3>Apakah anda yakin ingin memposting status berikut?</h3>
    <h5>{{ nama }}</h5>
    <p>{{ pesan }}</p>
    
    <form action="" method="POST">
        {% csrf_token %}
        <input id="ya" type="submit" value="Ya" class="button my-4">
    </form>

    <form action="/" method="GET">
        <input id="no" type="submit" value="Batalkan" class="button my-4">
    </form>

</body>

status/templates/home.html
<!DOCTYPE html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>

<section class="p-5 justify-content-center">
	<h1>Apa kabar?</h1>
	<form action="" method="post" enctype="multipart/form-data" novalidate>
		{% csrf_token %}
		<table class="table mx-5" style="width:90vw">
			{{ form.as_table }}
			<tr>
				<td>&nbsp;</td>
				<td><input id="submit" type="submit" value="Tambah Status" class="button my-4"></td>
			</tr>
		</table>
	</form>
</section>
<section>
    {% for i in status %}
	<div id='card' class="card w-75" style="background-color:{{i.color}}">
		<div class="card-body">
		  <h5 class="card-title">{{ i.nama }}</h5>
		  <p class="card-text">{{ i.pesan }}</p>
		  <form action="color/{{i.id}}/" method="POST">
			{% csrf_token %}
			<input name="ganti" type="submit" value="Ganti warna" class="button my-4">
		</form>
		</div>
	</div>
	{% endfor %}
</section>

templates/base.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        {% block style %}{% endblock %}
        
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
    {% block content %}
    {% endblock %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script src="https://code.iconify.design/1/1.0.4/iconify.min.js"></script>
    <script
        src="https://code.jquery.com/jquery-3.5.0.min.js"
        integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ="
        crossorigin="anonymous">
    </script>
    {% block script %}
    {% endblock %}
    </body>
</html>